name: Runs the tests

on:
  push:
    branches:
      - proto-without-grpc

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Polypheny
        uses: actions/checkout@v4
        with:
          repository: polypheny/Polypheny-DB
          path: db
          ref: proto-without-grpc

      - name: Checkout Polypheny-Prism-API
        uses: actions/checkout@v4
        with:
          repository: polypheny/Polypheny-Prism-API
          path: Polypheny-Prism-API

      - name: Checkout driver
        uses: actions/checkout@v4
        with:
          path: main

      - name: Build Polypheny
        run: |
          ./gradlew build -x test -x licensee
        working-directory: db

      - name: Download protobuf
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.0/protoc-26.0-linux-x86_64.zip
          unzip protoc-26.0-linux-x86_64.zip
          realpath bin/protoc
        working-directory: Polypheny-Prism-API

      - name: Build Protobuf Files
        run: bin/protoc -I proto --experimental_allow_proto3_optional --python_out . proto/polyprism/*.proto
        working-directory: Polypheny-Prism-API

      - name: Install driver dependencies
        run: pip install -r requirements.txt
        working-directory: main

      - name: Run tests
        run: pytest
        env:
          POLYPHENY_JAR: ../db/dbms/lib/dbms-0.10.0-SNAPSHOT.jar
        working-directory: main
